spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-produtodb
    username: produto
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
